/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ican_ytx_com_andoridmeidademuxerandmuxer_MediaUtils */

#ifndef _Included_ican_ytx_com_andoridmediademuxerandmuxer_MediaUtils
#define _Included_ican_ytx_com_andoridmediademuxerandmuxer_MediaUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ican_ytx_com_andoridmeidademuxerandmuxer_MediaUtils
 * Method:    demuxer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ican_ytx_com_andoridmediademuxerandmuxer_MediaUtils_demuxer
        (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     ican_ytx_com_andoridmeidademuxerandmuxer_MediaUtils
 * Method:    muxer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ican_ytx_com_andoridmediademuxerandmuxer_MediaUtils_muxer
        (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
